name: '🚀 Feature Request'
description: Propose a new idea, feature, or enhancement
title: '[Feat]: '
labels: ['enhancement']
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: E.g., I'm frustrated when I can't export my data to CSV...
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: A clear and concise description of what you want to happen.
  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      options:
        - Low
        - Medium
        - High
